# Travis CI

## Use Ruby language
language: ruby

## Use these RVM versions
rvm:
- 2.3.0

## Speeds up installation
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

## Route your build to the container-based infrastructure for a faster build
sudo: false

## Run this script before everything else
before_script:
 - chmod +x ./server.rb

## Run main script
script:
 - cat Gemfile.lock
 - rake travis

## Branch whitelist
branches:
  only:
  - master
